### ISSUE TITLE
Build on macOS missing 7zip-bin-mac

### ISSUE THREAD

**Issue by 0wnrepo** [matthewjamesr/hush-ng#1]
npm install 7zip-bin-mac is missing

```
user-mb:~ user$ cd ~/hush-ng/
user-mb:hush-ng user$ npm install

> rabin-bindings@1.7.3 install /Users/user/hush-ng/node_modules/rabin-bindings
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.3.0
prebuild-install info looking for local prebuild @ prebuilds/rabin-bindings-v1.7.3-node-v59-darwin-x64.tar.gz
prebuild-install info looking for cached prebuild @ /Users/user/.npm/_prebuilds/https-github.com-develar-rabin-bindings-releases-download-v1.7.3-rabin-bindings-v1.7.3-node-v59-darwin-x64.tar.gz
prebuild-install http request GET https://github.com/develar/rabin-bindings/releases/download/v1.7.3/rabin-bindings-v1.7.3-node-v59-darwin-x64.tar.gz
prebuild-install http 404 https://github.com/develar/rabin-bindings/releases/download/v1.7.3/rabin-bindings-v1.7.3-node-v59-darwin-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=9.3.0 runtime=node arch=x64 platform=darwin)
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/rabin-bindings/bindings.o
  CXX(target) Release/obj.target/rabin-bindings/src/rabin.o
  CXX(target) Release/obj.target/rabin-bindings/src/rabin_wrap.o
  SOLINK_MODULE(target) Release/rabin-bindings.node

> uglifyjs-webpack-plugin@0.4.6 postinstall /Users/user/hush-ng/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js


> electron@1.7.8 postinstall /Users/user/hush-ng/node_modules/electron
> node install.js

npm WARN hush-ng@0.0.0 No repository field.
npm WARN hush-ng@0.0.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@2.1.1 (node_modules/7zip-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@2.1.1: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})

added 1115 packages in 69.868s
user-mb:hush-ng user$ npm run dev

> hush-ng@0.0.0 dev /Users/user/hush-ng
> node .electron-vue/dev-runner.js


         ___                      __
   __   /\_ \       __     ___   /\ \__    _ __    ___     ___
 / ,.`\ \//\ \    / ,.`\  /'___\ \ \ ,_\  /\` __\ / __`\ /' _ `\   _______
/\  __/   \_\ \_ /\  __/ /\ \__/  \ \ \/  \ \ \/ /\ \_\ \/\ \/\ \ /\______\
\ \____\  /\____\\ \____\\ \____\  \ \ \_  \ \_\ \ \____/\ \_\ \_\\/______/
 \/____/  \/____/ \/____/ \/____/   \ \__\  \/_/  \/___/  \/_/\/_/
                                     \/__/


 __  __  __  __     __
/\ \/\ \/\ \/\ \  / ,.`\
\ \ \/ |\ \ \_\ \/\  __/
 \ \___/ \ \____/\ \____\
  \/__/   \/___/  \/____/

  getting ready...

The `setup` option is deprecated and will be removed in v3. Please update your config to use `before`
┏ Main Process ---------------

  compiling...

┗ ----------------------------

┏ Renderer Process -----------

  Hash: f44df5a89e1bb6965de5
  Version: webpack 3.8.1
  Time: 6257ms
                             Asset       Size  Chunks                    Chunk Names
             imgs/logo--assets.png    18.8 kB          [emitted]
  imgs/hush-icon-white--assets.png    17.7 kB          [emitted]
                       renderer.js    1.47 MB       0  [emitted]  [big]  renderer
                        index.html  399 bytes          [emitted]
     [0] ./node_modules/vue-hot-reload-api/dist/index.js 6.06 kB {0} [built]
     [2] ./node_modules/vue/dist/vue.esm.js 285 kB {0} [built]
     [5] ./node_modules/vue-loader/lib/component-normalizer.js 2.9 kB {0} [built]
    [25] ./src/renderer/store/modules/index.js 238 bytes {0} [built]
    [26] multi ./.electron-vue/dev-client ./src/renderer/main.js 40 bytes {0} [built]
    [27] ./.electron-vue/dev-client.js 731 bytes {0} [built]
    [28] (webpack)-hot-middleware/client.js?noInfo=true&reload=true 7.04 kB {0} [built]
    [29] (webpack)/buildin/module.js 495 bytes {0} [built]
    [30] external "querystring" 42 bytes {0} [not cacheable]
    [39] ./src/renderer/main.js 382 bytes {0} [built]
    [40] external "axios" 42 bytes {0} [not cacheable]
    [41] ./src/renderer/App.vue 1.97 kB {0} [built]
    [46] ./src/renderer/router/index.js 471 bytes {0} [built]
    [89] ./src/renderer/store/index.js 202 bytes {0} [built]
    [92] external "vue-electron" 42 bytes {0} [not cacheable]
      + 78 hidden modules
  Child html-webpack-plugin for "index.html":
           Asset     Size  Chunks  Chunk Names
      index.html  1.45 MB       0
         [0] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.ejs 1.26 kB {0} [built]
         [1] ./node_modules/lodash/lodash.js 540 kB {0} [built]
         [2] (webpack)/buildin/module.js 495 bytes {0} [built]

┗ ----------------------------

┏ Main Process ---------------

  Hash: a8fa30f18d6c25cee086
  Version: webpack 3.8.1
  Time: 6680ms
    Asset    Size  Chunks             Chunk Names
  main.js  186 kB       0  [emitted]  main
     [0] external "path" 42 bytes {0} [not cacheable]
     [1] external "fs" 42 bytes {0} [not cacheable]
     [2] external "electron" 42 bytes {0} [not cacheable]
    [13] ./node_modules/electron-devtools-installer/dist/utils.js 1.93 kB {0} [built]
    [14] ./src/main/index.js 804 bytes {0} [built]
    [15] multi ./src/main/index.dev.js ./src/main/index.js 40 bytes {0} [built]
    [16] ./src/main/index.dev.js 403 bytes {0} [built]
    [17] ./node_modules/electron-debug/index.js 2.19 kB {0} [built]
    [18] ./node_modules/electron-localshortcut/index.js 8.39 kB {0} [built]
    [28] ./node_modules/electron-is-dev/index.js 256 bytes {0} [built]
    [29] ./node_modules/devtron/api.js 1.26 kB {0} [optional] [built]
    [30] ./node_modules/electron-devtools-installer/dist/index.js 4.82 kB {0} [built]
    [31] ./node_modules/semver/semver.js 35.7 kB {0} [built]
    [32] ./node_modules/electron-devtools-installer/dist/downloadChromeExtension.js 2.31 kB {0} [built]
    [43] ./node_modules/cross-unzip/index.js 1.53 kB {0} [built]
      + 33 hidden modules

┗ ----------------------------

┏ Electron -------------------

  Debugger listening on port 5858.
  Warning: This is an experimental feature and could change at any time.
  To start debugging, open the following URL in Chrome:
      chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:5858/c71b658b-133b-45ed-944d-b936ebcd01b0

┗ ----------------------------

^Cuser-mb:hush-ng user$ npm run build

> hush-ng@0.0.0 build /Users/user/hush-ng
> node .electron-vue/build.js && electron-builder


 ___              __
/\_ \       __   /\ \__     ____
\//\ \    / ,.`\ \ \ ,_\   / ,__\  _______
  \_\ \_ /\  __/  \ \ \/  /\__, `\/\______\
  /\____\\ \____\  \ \ \_ \/\____/\/______/
  \/____/ \/____/   \ \__\ \/___/
                     \/__/

 __                       ___       __
/\ \       __  __   __   /\_ \     /\ \
\ \ \____ /\ \/\ \ /\_\  \//\ \    \_\ \
 \ \  ,. \\ \ \_\ \\/\ \   \_\ \_ /\ ,. \
  \ \____/ \ \____/ \ \ \  /\____\\ \____\
   \/___/   \/___/   \/_/  \/____/ \/___ /


  ✔ building main process
  ✔ building renderer process



Hash: ddd7ea4a186ae8b04f78
Version: webpack 3.8.1
Time: 1399ms
  Asset     Size  Chunks             Chunk Names
main.js  1.06 kB       0  [emitted]  main
   [0] ./src/main/index.js 804 bytes {0} [built]
   [1] external "electron" 42 bytes {0} [not cacheable]
   [2] external "path" 42 bytes {0} [not cacheable]

Hash: 18e8e3b5800f3074c524
Version: webpack 3.8.1
Time: 19384ms
                           Asset       Size  Chunks             Chunk Names
           imgs/logo--assets.png    18.8 kB          [emitted]
imgs/hush-icon-white--assets.png    17.7 kB          [emitted]
                     renderer.js     125 kB       0  [emitted]  renderer
                      styles.css    8.87 kB       0  [emitted]  renderer
                      index.html  349 bytes          [emitted]
   [1] ./node_modules/vue-loader/lib/component-normalizer.js 2.9 kB {0} [built]
   [3] ./node_modules/vue/dist/vue.esm.js 285 kB {0} [built]
  [12] ./src/renderer/store/modules/index.js 238 bytes {0} [built]
  [13] ./src/renderer/main.js 382 bytes {0} [built]
  [14] external "axios" 42 bytes {0} [not cacheable]
  [15] ./src/renderer/App.vue 1.31 kB {0} [built]
  [16] ./node_modules/extract-text-webpack-plugin/dist/loader.js?{"omit":1,"remove":true}!./node_modules/vue-style-loader!./node_modules/css-loader?minimize!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-72e85f2f","scoped":false,"hasInlineConfig":false}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/renderer/App.vue 41 bytes {0} [built]
  [17] ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/renderer/App.vue 39 bytes {0} [built]
  [18] ./node_modules/vue-loader/lib/template-compiler?{"id":"data-v-72e85f2f","hasScoped":false,"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./src/renderer/App.vue 268 bytes {0} [built]
  [19] ./src/renderer/router/index.js 471 bytes {0} [built]
  [20] external "vue-router" 42 bytes {0} [not cacheable]
  [21] ./src/renderer/components/LandingPage.vue 1.35 kB {0} [built]
  [33] ./src/renderer/components/Install.vue 1.34 kB {0} [built]
  [62] ./src/renderer/store/index.js 202 bytes {0} [built]
  [65] external "vue-electron" 42 bytes {0} [not cacheable]
    + 63 hidden modules
Child html-webpack-plugin for "index.html":
         Asset    Size  Chunks  Chunk Names
    index.html  568 kB       0
       [0] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.ejs 1.26 kB {0} [built]
       [1] ./node_modules/lodash/lodash.js 540 kB {0} [built]
       [2] (webpack)/buildin/module.js 495 bytes {0} [built]
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js?minimize!node_modules/vue-loader/lib/style-compiler/index.js?{"vue":true,"id":"data-v-72e85f2f","scoped":false,"hasInlineConfig":false}!node_modules/vue-loader/lib/selector.js?type=styles&index=0!src/renderer/App.vue:
       [0] ./node_modules/css-loader?minimize!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-72e85f2f","scoped":false,"hasInlineConfig":false}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/renderer/App.vue 166 bytes {0} [built]
       [1] ./node_modules/css-loader/lib/css-base.js 2.26 kB {0} [built]
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js?minimize!node_modules/vue-loader/lib/style-compiler/index.js?{"vue":true,"id":"data-v-9bc6a496","scoped":false,"hasInlineConfig":false}!node_modules/vue-loader/lib/selector.js?type=styles&index=0!src/renderer/components/Wallet.vue:
       [0] ./node_modules/css-loader?minimize!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-9bc6a496","scoped":false,"hasInlineConfig":false}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/renderer/components/Wallet.vue 2.42 kB {0} [built]
       [1] ./node_modules/css-loader/lib/css-base.js 2.26 kB {0} [built]
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js?minimize!node_modules/vue-loader/lib/style-compiler/index.js?{"vue":true,"id":"data-v-7cbccc92","scoped":false,"hasInlineConfig":false}!node_modules/vue-loader/lib/selector.js?type=styles&index=0!src/renderer/components/Install.vue:
       [0] ./node_modules/css-loader?minimize!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-7cbccc92","scoped":false,"hasInlineConfig":false}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/renderer/components/Install.vue 1.96 kB {0} [built]
       [1] ./node_modules/css-loader/lib/css-base.js 2.26 kB {0} [built]
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js?minimize!node_modules/vue-loader/lib/style-compiler/index.js?{"vue":true,"id":"data-v-5bec883e","scoped":false,"hasInlineConfig":false}!node_modules/vue-loader/lib/selector.js?type=styles&index=0!src/renderer/components/LandingPage.vue:
       [0] ./node_modules/css-loader?minimize!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-5bec883e","scoped":false,"hasInlineConfig":false}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/renderer/components/LandingPage.vue 1.43 kB {0} [built]
       [1] ./node_modules/css-loader/lib/css-base.js 2.26 kB {0} [built]
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js?minimize!node_modules/vue-loader/lib/style-compiler/index.js?{"vue":true,"id":"data-v-59c99cc2","scoped":false,"hasInlineConfig":false}!node_modules/vue-loader/lib/selector.js?type=styles&index=0!src/renderer/components/Wallet/Addresses.vue:
       [0] ./node_modules/css-loader?minimize!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-59c99cc2","scoped":false,"hasInlineConfig":false}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/renderer/components/Wallet/Addresses.vue 1.76 kB {0} [built]
       [1] ./node_modules/css-loader/lib/css-base.js 2.26 kB {0} [built]
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js?minimize!node_modules/vue-loader/lib/style-compiler/index.js?{"vue":true,"id":"data-v-7a5623c0","scoped":false,"hasInlineConfig":false}!node_modules/vue-loader/lib/selector.js?type=styles&index=0!src/renderer/components/shared/Menu.vue:
       [0] ./node_modules/css-loader?minimize!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-7a5623c0","scoped":false,"hasInlineConfig":false}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/renderer/components/shared/Menu.vue 491 bytes {0} [built]
       [1] ./node_modules/css-loader/lib/css-base.js 2.26 kB {0} [built]
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js?minimize!node_modules/vue-loader/lib/style-compiler/index.js?{"vue":true,"id":"data-v-81b2968a","scoped":false,"hasInlineConfig":false}!node_modules/vue-loader/lib/selector.js?type=styles&index=0!src/renderer/components/Wallet/WalletMenu.vue:
       [0] ./node_modules/css-loader?minimize!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-81b2968a","scoped":false,"hasInlineConfig":false}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/renderer/components/Wallet/WalletMenu.vue 1.21 kB {0} [built]
       [1] ./node_modules/css-loader/lib/css-base.js 2.26 kB {0} [built]
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js?minimize!node_modules/vue-loader/lib/style-compiler/index.js?{"vue":true,"id":"data-v-e6b2c034","scoped":false,"hasInlineConfig":false}!node_modules/vue-loader/lib/selector.js?type=styles&index=0!src/renderer/components/shared/CloseButton.vue:
       [0] ./node_modules/css-loader?minimize!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-e6b2c034","scoped":false,"hasInlineConfig":false}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/renderer/components/shared/CloseButton.vue 690 bytes {0} [built]
       [1] ./node_modules/css-loader/lib/css-base.js 2.26 kB {0} [built]
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js?minimize!node_modules/vue-loader/lib/style-compiler/index.js?{"vue":true,"id":"data-v-19595184","scoped":true,"hasInlineConfig":false}!node_modules/vue-loader/lib/selector.js?type=styles&index=0!src/renderer/components/LandingPage/SystemInformation.vue:
       [0] ./node_modules/css-loader?minimize!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-19595184","scoped":true,"hasInlineConfig":false}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/renderer/components/LandingPage/SystemInformation.vue 488 bytes {0} [built]
       [1] ./node_modules/css-loader/lib/css-base.js 2.26 kB {0} [built]


 OKAY  take it away `electron-builder`

electron-builder 19.45.5
No native production dependencies
Packaging for darwin x64 using electron 1.7.8 to build/mac
Downloading tmp-8344-1-SHASUMS256.txt-1.7.8
[============================================>] 100.0% of 2.93 kB (2.93 kB/s)
⚠️  Mac Developer is used to sign app — it is only for development and testing, not for production
Signing app (identity: uid Mac Developer: user@email.com (id))
Building macOS zip
Building DMG
Error: Cannot find module '7zip-bin-mac'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/user/hush-ng/node_modules/7zip-bin/index.js:13:67)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at _load_zipBin (/Users/user/hush-ng/node_modules/electron-builder/out/targets/archive.js:93:22)
    at /Users/user/hush-ng/node_modules/electron-builder/src/targets/archive.ts:151:5
From previous event:
    at archive (/Users/user/hush-ng/node_modules/electron-builder/out/targets/archive.js:82:22)
    at /Users/user/hush-ng/node_modules/electron-builder/src/targets/ArchiveTarget.ts:34:13
    at Generator.next (<anonymous>)
From previous event:
    at ArchiveTarget.build (/Users/user/hush-ng/node_modules/electron-builder/out/targets/ArchiveTarget.js:74:11)
    at taskManager.addTask.default.map.it (/Users/user/hush-ng/node_modules/electron-builder/src/platformPackager.ts:120:85)
From previous event:
    at MacPackager.packageInDistributableFormat (/Users/user/hush-ng/node_modules/electron-builder/src/platformPackager.ts:120:41)
    at /Users/user/hush-ng/node_modules/electron-builder/src/macPackager.ts:97:26
From previous event:
    at /Users/user/hush-ng/node_modules/electron-builder/src/macPackager.ts:97:10
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Users/user/hush-ng/node_modules/electron-builder/out/macPackager.js:200:11)
    at /Users/user/hush-ng/node_modules/electron-builder/src/packager.ts:314:24
From previous event:
    at Packager.doBuild (/Users/user/hush-ng/node_modules/electron-builder/out/packager.js:378:11)
    at /Users/user/hush-ng/node_modules/electron-builder/src/packager.ts:240:52
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (/Users/user/hush-ng/node_modules/electron-builder/out/packager.js:307:11)
    at /Users/user/hush-ng/node_modules/electron-builder/src/builder.ts:278:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/Users/user/hush-ng/node_modules/electron-builder/out/builder.js:68:21)
    at then (/Users/user/hush-ng/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at runCallback (timers.js:773:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate [as _immediateCallback] (timers.js:711:5)
From previous event:
    at Object.args [as handler] (/Users/user/hush-ng/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at Object.runCommand (/Users/user/hush-ng/node_modules/yargs/lib/command.js:228:22)
    at Object.parseArgs [as _parseArgs] (/Users/user/hush-ng/node_modules/yargs/yargs.js:1041:24)
    at Object.get [as argv] (/Users/user/hush-ng/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/Users/user/hush-ng/node_modules/electron-builder/src/cli/cli.ts:43:15)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! hush-ng@0.0.0 build: `node .electron-vue/build.js && electron-builder`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the hush-ng@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2017-12-29T07_57_40_391Z-debug.log

```

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/9.3.0_1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.6.0
3 info using node@v9.3.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle hush-ng@0.0.0~prebuild: hush-ng@0.0.0
6 info lifecycle hush-ng@0.0.0~build: hush-ng@0.0.0
7 verbose lifecycle hush-ng@0.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle hush-ng@0.0.0~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/good/hush-ng/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Library/TeX/texbin:/opt/metasploit-framework/bin:/opt/metasploit-framework/bin
9 verbose lifecycle hush-ng@0.0.0~build: CWD: /Users/good/hush-ng
10 silly lifecycle hush-ng@0.0.0~build: Args: [ '-c', 'node .electron-vue/build.js && electron-builder' ]
11 silly lifecycle hush-ng@0.0.0~build: Returned: code: 255  signal: null
12 info lifecycle hush-ng@0.0.0~build: Failed to exec build script
13 verbose stack Error: hush-ng@0.0.0 build: `node .electron-vue/build.js && electron-builder`
13 verbose stack Exit status 255
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:159:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:159:13)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid hush-ng@0.0.0
15 verbose cwd /Users/good/hush-ng
16 verbose Darwin 16.4.0
17 verbose argv "/usr/local/Cellar/node/9.3.0_1/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v9.3.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 255
22 error hush-ng@0.0.0 build: `node .electron-vue/build.js && electron-builder`
22 error Exit status 255
23 error Failed at the hush-ng@0.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 255, true ]

```

**Comment by matthewjamesr** [comment]
Thank you for the detailed error log and the fixing PR. Merged 💯
